1次元配列

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)
type(a)

[1 2 3]


numpy.ndarray

配列の生成と部分取得

In [3]:
import numpy as np
a = np.array([[0,1,2],[3,4,5]])
b = np.array([1,2,3,4])
print(a[:,[0,2]],b.shape)

[[0 2]
 [3 5]] (4,)


arange関数、eye関数

In [1]:
import numpy as np
#1から10まで2ごとに数字をいれたベクトルaを作成
a = np.arange(1,11,2)
#4行4列の単位行列bを作成
b = np.eye(4)
print(a)
print(b)

[1 3 5 7 9]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


linespace関数を用いた均等割り

In [3]:
import numpy as np
#1行6列のネイピア数の行列aを作成
a = np.full((1,6),np.e).T.ravel()
#0から1.25までを6糖分した行列bを作成
b = np.linspace(0,1.25,6)
#行列a,bを列方向に結合
c = np.hstack([a,b])
print(a)
print(b)
print(c)


[2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183]
[0.   0.25 0.5  0.75 1.   1.25]
[2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 0.         0.25       0.5        0.75       1.         1.25      ]


ブロードキャストとユニバーサルファンクション

In [2]:
import numpy as np
a = np.array([9,99,999,9999])
a += 1
print(a)
a *= 10
print(a)
b =np.log10(a)
print(b)
print(a[2],b[3])

[   10   100  1000 10000]
[   100   1000  10000 100000]
[2. 3. 4. 5.]
10000 5.0


ドット積

In [ ]:
import numpy as np
a = np.array([0,1])
b = np.array([[2],[3]])
c = np.array([[4,5],[6,7]])
#d = a × b
d = a @ b
e = np.dot(c,a)
f = c @ a
print(d,e,f)