参照、型変換

In [9]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(a)
print(type(a))
print(a.shape)
print(b.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
(3,)


In [27]:
#reshape
c1 = np.array([0,1,2,3,4,5])
c2 = c1.reshape((2,3))
print(c2)

#コピー
c3 = c2.ravel()
print(c3)
c4 = c2.flatten()
print(c4)

#型変換
c5 = np.array([1,2],dtype = np.int16)
print(c5.dtype)
c6 = c5.astype(np.float16)
print(c6.dtype)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
int16
float16


値の取得

In [33]:
import numpy as np
a = np.array([[0, 1, 2], [3, 4, 5]])
b = np.array([0, 1, 2])
#値の取得
print(a[-1:, [0, 2]], b.dtype)
#データの代入
a[1,0] = 10
print(a[-1:, [0, 2]], b.dtype)

[[3 5]] int32
[[10  5]] int32


配列の生成

In [35]:
import numpy as np
#1から11の手前まで2ずつインクリメントした行列
a = np.arange(1, 11, 2)
#4×4の単位行列
b = np.eye(4)
print(a)
print(b)
print(a[3], b[3, 3])

[1 3 5 7 9]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
7 1.0


ドット積

In [37]:
a = np.array([0, 1])
b = np.array([[4, 5], [6, 7]])
print(a@b)
print(np.dot(a,b))

[6 7]
[6 7]
